### ISSUE TITLE
Can MindSQL run without Internet？

### ISSUE THREAD

**Issue by kuazhangxiaoai** [Mindinventory/MindSQL#14]
So great work! Do you know how can I run MindSQL locally?
Thanks for your answers!

**Comment by ishika-mi** [comment]
@kuazhangxiaoai 

You'll need an internet connection to clone the MindSQL repository from GitHub and to install any required dependencies. If you want to use language models like those from OpenAI or GoogleGenAI or Anthropic, which are accessed through cloud services or APIs, you'll need to be online. Once you've installed MindSQL and its dependencies, you can run it without needing an internet connection. If you're using local models like LLaMA or ones from Hugging Face that you've downloaded, you can work completely offline.
