### ISSUE TITLE
How does this differ from Vanna?

### ISSUE THREAD

**Issue by zainhoda** [Mindinventory/MindSQL#3]
Hey there! This seems eerily similar to Vanna:

https://github.com/vanna-ai/vanna

I’m curious why our projects need to be different

**Comment by siddhant-mi** [comment]
So that you get your team to work on some features and we get out team to work on features so collaboratively we can help the community to use both our projects in future with different functionalities. 

We are sure your team is amazing same as ours to serve best to community.

**Comment by zainhoda** [comment]
That's fine -- you have that right. But note that per the terms of the MIT License, you must retain the copyright and permission notice:

https://github.com/vanna-ai/vanna/blob/main/LICENSE

**Comment by Sammindinventory** [comment]
Great looking forward to collaborating soon. Will connect over LinkedIn.

**Comment by jdbohrman** [comment]
@zainhoda I'm sorry but what ways do you find it similar? The implementation is totally different, and frankly I find MindSQL's to be a lot smoother. This comes off super weird not going to lie.
