### ISSUE TITLE
Support for wikisql or open surce llms

### ISSUE THREAD

**Issue by krupalshah** [Mindinventory/MindSQL#7]
Hi, good work. Are there plans to add support for any open source llms that does not require api keys?

**Comment by Sammindinventory** [comment]
Hi Krupal,

It supports open source LLMs too.

**Comment by krupalshah** [comment]
Ok. How to use? Will I need api keys in that case?

**Comment by Sammindinventory** [comment]
@krupalshah No you wouldnt need any API keys for Self hosted Open source models.
